[package]
name = "raffine"
version = "0.1.0"
edition = "2021"
authors = ["zwishingbjfu@gmail.com"]
description = "A 2D affine transformation library for Rust"
license = "MIT"
repository = "https://gitee.com/zhangwishing/raffine"
keywords = ["affine", "transformation",]
readme = "README.md"

[dependencies]
thiserror = "2.0.12"
